// <auto-generated />
using System;
using BudgetTracker.Domain.Enums;
using BudgetTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414101654_RemoveBudgetPeriodColumns")]
    partial class RemoveBudgetPeriodColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<CurrencyCode>("Currency")
                        .HasColumnType("currency_code")
                        .HasColumnName("currency");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("Currency")
                        .HasDatabaseName("ix_budgets_currency");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_name");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.BudgetOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CreditAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("credit_amount");

                    b.Property<decimal?>("DebitAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("debit_amount");

                    b.Property<OperationKind>("Kind")
                        .HasColumnType("operation_kind")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("SourceBudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_budget_id");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategory_id");

                    b.Property<Guid?>("TargetBudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_budget_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_budget_operations");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_budget_operations_occurred_at");

                    b.HasIndex("BudgetId", "OccurredAt")
                        .HasDatabaseName("ix_budget_operations_budget_id_occurred_at");

                    b.HasIndex("Kind", "OccurredAt")
                        .HasDatabaseName("ix_budget_operations_kind_occurred_at");

                    b.HasIndex("SourceBudgetId", "OccurredAt")
                        .HasDatabaseName("ix_budget_operations_source_budget_id_occurred_at");

                    b.HasIndex("SubcategoryId", "OccurredAt")
                        .HasDatabaseName("ix_budget_operations_subcategory_id_occurred_at");

                    b.HasIndex("TargetBudgetId", "OccurredAt")
                        .HasDatabaseName("ix_budget_operations_target_budget_id_occurred_at");

                    b.ToTable("budget_operations", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<CategoryKind>("Kind")
                        .HasColumnType("category_kind")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_categories_kind");

                    b.HasIndex("Kind", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_kind_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subcategories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_subcategories_category_id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subcategories_category_id_name");

                    b.ToTable("subcategories", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.BudgetOperation", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Entities.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_budget_operations_budgets_budget_id");

                    b.HasOne("BudgetTracker.Domain.Entities.Budget", null)
                        .WithMany()
                        .HasForeignKey("SourceBudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_budget_operations_budgets_source_budget_id");

                    b.HasOne("BudgetTracker.Domain.Entities.Subcategory", null)
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_budget_operations_subcategories_subcategory_id");

                    b.HasOne("BudgetTracker.Domain.Entities.Budget", null)
                        .WithMany()
                        .HasForeignKey("TargetBudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_budget_operations_budgets_target_budget_id");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Entities.Subcategory", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subcategories_categories_category_id");
                });
#pragma warning restore 612, 618
        }
    }
}
